### ISSUE TITLE
Windows 10 npm install issue

### ISSUE THREAD

**Issue by echoparkbaby** [felixbrucker/chia-api#1]
not able to install this on Windows 10. Getting this error.

de ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/felixbrucker/chia-api.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by echoparkbaby** [comment]
hey sorry, I think the error is due to GIT not being installed on my windows box.

**Comment by felixbrucker** [comment]
Yes, as of right now you also need git, but in the near future this wont be necessary anymore 👍
